require("prototypes.space-age.vulcanus.vulcanus-wolframite")
require("prototypes.space-age.vulcanus.vulcanus-samarskite")
require("prototypes.space-age.fulgora.fulgora-brannerite")
require("prototypes.space-age.fulgora.fulgora-rheniite")
require("prototypes.space-age.aquilo.aquilo-antimonite")
require("prototypes.space-age.aquilo.aquilo-germanite")